name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: step1
        run: |
          output=$(python test.py)
          echo "::set-output name=status:$output"
          echo "${{ steps.step1.outputs.status }} asdfasdfadsf"

     # - run: |
      #    echo "${{ steps.step1.outputs.status }} asdfasdfadsf"
