name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: step1
        run: |
          output=$(python test.py v2.21)
          echo "::set-output name=changelog::$output"
          echo $output
      
      - name: Set selected color
        run: |
          output=$(python test.py v2.21)
          echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

     # - run: |
      #    echo "${{ steps.step1.outputs.status }} asdfasdfadsf"
