name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          output=$(python test.py v2.21)
          compare='argument v2.22'
          if [ "$output" = "$compare" ]; then
            echo '::set-output name=changelog::success'
          
          else
            echo '::set-output name=changelog::failed'
          fi
        id: step1
          
      - if: steps.step1.outputs.changelog != 'success'
        run: |
          echo ${{ steps.step1.outputs.changelog }}
          exit 1
      
      - name: Set selected color
        run: |
          output=$(python test.py v2.21)
          echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
        
      - name: Get changelog
        run: |
          echo "The selected color is ${{ steps.step1.outputs.changelog }}"
          echo ${{ steps.step1.outputs.changelog }}

     # - run: |
      #    echo "${{ steps.step1.outputs.status }} asdfasdfadsf"
