name: Test-ML-Model

#triggers only when model.pkl is updated with a new ML model
on: push

jobs:
  test-ml-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install Cython
          pip install scikit-learn==0.21.2
      - run: |
          output=$(python test.py)
          condition='deploy'
          if [ "$output" = "$condition" ]; then
            echo '::set-output name=status::success'
          
          else
            echo '::set-output name=status::failed'
          fi
        id: model-test
        
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.GITHUB_TOKEN }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "ml_metric.txt"
