name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          output=$(python test.py)
          echo "::set-output name=status:$output"
        id: step1

      - run: |
          echo ${{ steps.check.outputs.status }}
